spring.application.name=paes-platform

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/paes_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=update

# Server Configuration
server.port=8080
